CREATE TABLE IF NOT EXISTS DIM_SUPPLIER (
		ID 		   INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
		NAME  	   VARCHAR(255)  NOT NULL,
		ADDRESS    VARCHAR(255)

);
CREATE INDEX IF NOT EXISTS DIM_SUPPLIER_NAME_INDEX ON DIM_SUPPLIER(NAME);

CREATE TABLE  IF NOT EXISTS DIM_PRODUCT (
		ID 		 INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
		NAME  	 VARCHAR(255),
		PRDT_TYPE  	 VARCHAR(255),
		EAN_CODE VARCHAR(255) NOT NULL
);
CREATE INDEX IF NOT EXISTS DIM_PRODUCT_EAN_CODE_INDEX ON DIM_PRODUCT(EAN_CODE);

CREATE TABLE IF NOT EXISTS DIM_EMPLOYEE_PURCHASER (
		ID 		   INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
		FIRST_NAME VARCHAR(255),
		LAST_NAME  VARCHAR(255),
		EMAIL      VARCHAR(255)  NOT NULL
);
CREATE INDEX IF NOT EXISTS DIM_EMP_PURCHASER_EMAIL_INDEX ON DIM_EMPLOYEE_PURCHASER(EMAIL);

CREATE TABLE IF NOT EXISTS DIM_DATE (
		ID 			    INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
		DATE_TIME 		DATE
);
CREATE INDEX IF NOT EXISTS DIM_DATE_INDEX ON DIM_DATE(DATE_TIME);

CREATE TABLE IF NOT EXISTS FACT_ORDER (
		ID 		             INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
		SUPPLIER_ID          VARCHAR(255) NOT NULL,
		EMP_PURCHASER_ID     VARCHAR(255) NOT NULL,
		PRODUCT_ID           VARCHAR(255) NOT NULL,
		DATE_ID              VARCHAR(255) NOT NULL,
		QUANTITY             INT NOT NULL,
		TOTAL_AMOUNT         DECIMAL NOT NULL     
);
ALTER TABLE FACT_ORDER ADD CONSTRAINT IF NOT EXISTS FACT_ORDER_SUPPLIER_FK FOREIGN KEY(SUPPLIER_ID) REFERENCES DIM_SUPPLIER(ID) ;
ALTER TABLE FACT_ORDER ADD CONSTRAINT IF NOT EXISTS FACT_ORDER_EMP_PURCHASER_FK FOREIGN KEY(EMP_PURCHASER_ID) REFERENCES DIM_EMPLOYEE_PURCHASER(ID) ;
ALTER TABLE FACT_ORDER ADD CONSTRAINT IF NOT EXISTS FACT_ORDER_PRODUCT_FK FOREIGN KEY(PRODUCT_ID) REFERENCES DIM_PRODUCT(ID) ;
ALTER TABLE FACT_ORDER ADD CONSTRAINT IF NOT EXISTS FACT_ORDER_DATE_FK FOREIGN KEY(DATE_ID) REFERENCES DIM_DATE(ID) ;
CREATE INDEX IF NOT EXISTS FACT_ORDER_SUPPLIER_ID_INDEX ON FACT_ORDER(SUPPLIER_ID);
CREATE INDEX IF NOT EXISTS FACT_ORDER_PRODUCT_ID_INDEX ON FACT_ORDER(PRODUCT_ID);
CREATE INDEX IF NOT EXISTS FACT_ORDER_EMP_PURCHASER_ID_INDEX ON FACT_ORDER(EMP_PURCHASER_ID);
CREATE INDEX IF NOT EXISTS FACT_ORDER_DATE_ID_INDEX ON FACT_ORDER(DATE_ID);